#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 28 07:39:47 2017

@author: tbrady
"""

def displayScoreboard(s):
    print('Place\tManager\tWin%\tProj.PF')
    for i in range(len(s)):
        print('{:<}\t{:<}\t{:<.3f}\t{:<.2f}'.format(i+1,s[i][0], s[i][1], s[i][2], s[i][3]))

##          0       1        2        3        4        5        6        7         8        9      
m =  [  'Tom',   'Ray', 'Chris',  'Ziad','Bashar', 'Jason',  'Mike',   'Cam','Brandon','Tyson']
w =  [      7,       6,       6,       6,       5,       7,       7,       3,       6,       7]
l =  [      5,       6,       6,       6,       7,       5,       5,       9,       6,       5]
pf = [1270.90, 1172.94, 1298.48, 1076.96, 1355.24, 1337.42, 1336.48, 1190.86, 1332.20, 1284.36]
pa = [1231.92, 1309.76, 1283.52, 1208.78, 1419.80, 1185.96, 1264.68, 1285.72, 1210.42, 1255.28]
avg= [ 105.91,   97.75,  108.21,   89.75,  112.94,  111.45,  111.37,   99.24,  111.02,  107.03]
pos= [0,0,0,0,0,0,0,0,0,0]
wnew = w
lnew = l
pfnew= pf



## matchups
## 0 v 8
## 1 v 6
## 2 v 7
## 3 v 5
## 4 v 9
m0 = [[0,8],[8,0]]
m1 = [[1,6],[6,1]]
m2 = [[2,7],[7,2]]
m3 = [[3,5],[5,3]]
m4 = [[4,9],[9,4]]

w12s = []

for i in range(len(m)):
    pct = w[i]/(w[i]+l[i])
    w12s.append([m[i],pct,pf[i]])
    
w12s.sort(key = lambda l: (l[1], l[2]), reverse = True)

#displayScoreboard(w12s)


for i in range(32):
#    print(int((i & 1)/1),int((i & 2)/2),int((i & 4)/4),int((i & 8)/8),int((i & 16)/16))
    print('Winners: {}, {}, {}, {}, {}'.format(m[m0[int((i & 1)/1)][0]],
                                               m[m1[int((i & 2)/2)][0]],
                                               m[m2[int((i & 4)/4)][0]],
                                               m[m3[int((i & 8)/8)][0]],
                                               m[m4[int((i & 16)/16)][0]]))
    ns = []
    wnew = [7,6,6,6,5,7,7,3,6,7]
    lnew = [5,6,6,6,7,5,5,9,6,5]

    wnew[m0[int((i & 1)/1)][0]]   += 1
    lnew[m0[int((i & 1)/1)][1]]   += 1
    
    wnew[m1[int((i & 2)/2)][0]]   += 1
    lnew[m1[int((i & 2)/2)][1]]   += 1
    
    wnew[m2[int((i & 4)/4)][0]]   += 1
    lnew[m2[int((i & 4)/4)][1]]   += 1
    
    wnew[m3[int((i & 8)/8)][0]]   += 1
    lnew[m3[int((i & 8)/8)][1]]   += 1
    
    wnew[m4[int((i & 16)/16)][0]]   += 1
    lnew[m4[int((i & 16)/16)][1]]   += 1
    


    for i in range(len(m)):
        pct = wnew[i]/(wnew[i]+lnew[i])
        ns.append([m[i],pct,pf[i]+avg[i],i])
      
    ns.sort(key = lambda l: (l[1], l[2]), reverse = True)

    for i in range(1,len(m)+1):
        pos[ns[i-1][3]] += i


    displayScoreboard(ns)
    print('------------------------------------------')

k = []
for i in range(len(m)):
    pos[i] /= 32
    k.append([m[i],pos[i]])

k.sort(key = lambda l: (l[1]))
for i in range(len(m)):
    print('{:<5} {}'.format(k[i][1],k[i][0]))







